import {
  Archive,
  Binary,
  Blocks,
  BookOpen,
  Box,
  Braces,
  Code2,
  Cog,
  Coffee,
  Cpu,
  Database,
  File,
  FileCheck,
  FileCode,
  FileCode2,
  FileSpreadsheet,
  FileText,
  FileType,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  Hash,
  Hexagon,
  Image,
  Lock,
  Music2,
  NotebookPen,
  Palette,
  Scroll,
  Settings,
  Shield,
  SquareFunction,
  Terminal,
  Video,
  Workflow,
} from 'lucide-react';
import type { FileIconData, FileIconMap } from '../types/types';

export const ICON_SIZE_CLASS = 'w-4 h-4 flex-shrink-0';

const FILE_ICON_MAP: FileIconMap = {
  js: { icon: FileCode },
  jsx: { icon: FileCode },
  mjs: { icon: FileCode },
  cjs: { icon: FileCode },
  ts: { icon: FileCode2 },
  tsx: { icon: FileCode2 },
  mts: { icon: FileCode2 },
  py: { icon: Code2 },
  pyw: { icon: Code2 },
  pyi: { icon: Code2 },
  ipynb: { icon: NotebookPen },
  rs: { icon: Cog },
  toml: { icon: Settings },
  go: { icon: Hexagon },
  rb: { icon: Gem },
  erb: { icon: Gem },
  php: { icon: Blocks },
  java: { icon: Coffee },
  jar: { icon: Coffee },
  kt: { icon: Hexagon },
  kts: { icon: Hexagon },
  c: { icon: Cpu },
  h: { icon: Cpu },
  cpp: { icon: Cpu },
  hpp: { icon: Cpu },
  cc: { icon: Cpu },
  cs: { icon: Hexagon },
  swift: { icon: Flame },
  lua: { icon: SquareFunction },
  r: { icon: FlaskConical },
  html: { icon: Globe },
  htm: { icon: Globe },
  css: { icon: Hash },
  scss: { icon: Hash },
  sass: { icon: Hash },
  less: { icon: Hash },
  vue: { icon: FileCode2 },
  svelte: { icon: FileCode2 },
  json: { icon: Braces },
  jsonc: { icon: Braces },
  json5: { icon: Braces },
  yaml: { icon: Settings },
  yml: { icon: Settings },
  xml: { icon: FileCode },
  csv: { icon: FileSpreadsheet },
  tsv: { icon: FileSpreadsheet },
  sql: { icon: Database },
  graphql: { icon: Workflow },
  gql: { icon: Workflow },
  proto: { icon: Box },
  env: { icon: Shield },
  md: { icon: BookOpen },
  mdx: { icon: BookOpen },
  txt: { icon: FileText },
  doc: { icon: FileText },
  docx: { icon: FileText },
  pdf: { icon: FileCheck },
  rtf: { icon: FileText },
  tex: { icon: Scroll },
  rst: { icon: FileText },
  sh: { icon: Terminal },
  bash: { icon: Terminal },
  zsh: { icon: Terminal },
  fish: { icon: Terminal },
  ps1: { icon: Terminal },
  bat: { icon: Terminal },
  cmd: { icon: Terminal },
  png: { icon: Image },
  jpg: { icon: Image },
  jpeg: { icon: Image },
  gif: { icon: Image },
  webp: { icon: Image },
  ico: { icon: Image },
  bmp: { icon: Image },
  tiff: { icon: Image },
  svg: { icon: Palette },
  mp3: { icon: Music2 },
  wav: { icon: Music2 },
  ogg: { icon: Music2 },
  flac: { icon: Music2 },
  aac: { icon: Music2 },
  m4a: { icon: Music2 },
  mp4: { icon: Video },
  mov: { icon: Video },
  avi: { icon: Video },
  webm: { icon: Video },
  mkv: { icon: Video },
  ttf: { icon: FileType },
  otf: { icon: FileType },
  woff: { icon: FileType },
  woff2: { icon: FileType },
  eot: { icon: FileType },
  zip: { icon: Archive },
  tar: { icon: Archive },
  gz: { icon: Archive },
  bz2: { icon: Archive },
  rar: { icon: Archive },
  '7z': { icon: Archive },
  lock: { icon: Lock },
  exe: { icon: Binary },
  bin: { icon: Binary },
  dll: { icon: Binary },
  so: { icon: Binary },
  dylib: { icon: Binary },
  wasm: { icon: Binary },
  ini: { icon: Settings },
  cfg: { icon: Settings },
  conf: { icon: Settings },
  log: { icon: Scroll },
  map: { icon: File },
};

const FILENAME_ICON_MAP: FileIconMap = {
  Dockerfile: { icon: Box },
  'docker-compose.yml': { icon: Box },
  'docker-compose.yaml': { icon: Box },
  '.dockerignore': { icon: Box },
  '.gitignore': { icon: Settings },
  '.gitmodules': { icon: Settings },
  '.gitattributes': { icon: Settings },
  '.editorconfig': { icon: Settings },
  '.prettierrc': { icon: Settings },
  '.prettierignore': { icon: Settings },
  '.eslintrc': { icon: Settings },
  '.eslintrc.js': { icon: Settings },
  '.eslintrc.json': { icon: Settings },
  '.eslintrc.cjs': { icon: Settings },
  'eslint.config.js': { icon: Settings },
  'eslint.config.mjs': { icon: Settings },
  '.env': { icon: Shield },
  '.env.local': { icon: Shield },
  '.env.development': { icon: Shield },
  '.env.production': { icon: Shield },
  '.env.example': { icon: Shield },
  'package.json': { icon: Braces },
  'package-lock.json': { icon: Lock },
  'yarn.lock': { icon: Lock },
  'pnpm-lock.yaml': { icon: Lock },
  'bun.lockb': { icon: Lock },
  'Cargo.toml': { icon: Cog },
  'Cargo.lock': { icon: Lock },
  Gemfile: { icon: Gem },
  'Gemfile.lock': { icon: Lock },
  Makefile: { icon: Terminal },
  'CMakeLists.txt': { icon: Cog },
  'tsconfig.json': { icon: Braces },
  'jsconfig.json': { icon: Braces },
  'vite.config.ts': { icon: Flame },
  'vite.config.js': { icon: Flame },
  'webpack.config.js': { icon: Cog },
  'tailwind.config.js': { icon: Hash },
  'tailwind.config.ts': { icon: Hash },
  'postcss.config.js': { icon: Cog },
  'babel.config.js': { icon: Settings },
  '.babelrc': { icon: Settings },
  'README.md': { icon: BookOpen },
  LICENSE: { icon: FileCheck },
  'LICENSE.md': { icon: FileCheck },
  'CHANGELOG.md': { icon: Scroll },
  'requirements.txt': { icon: FileText },
  'go.mod': { icon: Hexagon },
  'go.sum': { icon: Lock },
};

// Icon resolution is deterministic: exact filename, then .env prefixes, then extension, then fallback.
export function getFileIconData(filename: string): FileIconData {
  if (FILENAME_ICON_MAP[filename]) {
    return FILENAME_ICON_MAP[filename];
  }

  if (filename.startsWith('.env')) {
    return { icon: Shield };
  }

  const extension = filename.split('.').pop()?.toLowerCase();
  if (extension && FILE_ICON_MAP[extension]) {
    return FILE_ICON_MAP[extension];
  }

  return { icon: File };
}
